### PR TITLE
Fix: Set correct compiler.runtime based on GUI preferences

### LINKED ISSUE #233: [Bug] The linkage type generated during the dependencies compilation mismatches the project one
In one of my Visual Studio project, I'm compiling a static DLL, as you can see on the below project option:

image

However, when Conan compile my dependencies, it generates this configuration file:
```
[settings]
arch=x86_64
build_type=Debug
compiler=msvc
compiler.cppstd=20
compiler.runtime=dynamic    <== !!! This is not matching my project options !!!

compiler.runtime_type=Debug
compiler.version=193
os=Windows
```

As the Conan config file mismatches the one in my project option, I get this error during the linking time:

> Error LNK2038	mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in MyRPCClient.obj MyShellExt C:\Projets\branches\vs2022_dev\MyShellExt\libboost_thread.lib(thread.obj)	1

On the other hand, if I manually correct my config file as below:
```
[settings]
arch=x86_64
build_type=Debug
compiler=msvc
compiler.cppstd=20
compiler.runtime=static

compiler.runtime_type=Debug
compiler.version=193
os=Windows
```

the project compiles and links as expected.

Can you please fix that?

### PR DESCRIPTION
**Pull request by memsharded**
- Set compiler runtime based on Visual Studio settings.
- Trigger conan install when changing profiles contents.

Close https://github.com/conan-io/conan-vs-extension/issues/233

### CODE REVIEW

**Review by AbrilRBS — APPROVED** [review]
Ooops! Nice catch

**Comment by memsharded** [comment]
Did manual testing, seems to work fine.

File: ConanProfilesManager.cs [hunk 1]
```diff
@@ -97,6 +97,7 @@ public void GenerateProfilesForProject(Project project)
                                 IVCRulePropertyStorage generalRule = vcConfig.Rules.Item("ConfigurationGeneral") as IVCRulePropertyStorage;
                                 string languageStandard = generalRule == null ? null : generalRule.GetEvaluatedPropertyValue("LanguageStandard");
                                 string cppStd = getConanCppstd(languageStandard);
+                                string runtime = vcConfig.Evaluate("$(RuntimeLibrary)").ToString().Contains("DLL") ? "dynamic" : "static";
```
Comment (czoido) [inline ConanProfilesManager.cs]: I think this is evaluating always to static as `vcConfig.Evaluate("$(RuntimeLibrary)")` is not a valid way to get the runtime

**Review by AbrilRBS — APPROVED** [review]

**Review by danimtb — APPROVED** [review]
